name: Build Project

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies and compile on Ubuntu
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential libboost-all-dev

      - name: Compile code on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          g++ -std=c++20 -O3 -march=native *.cpp -o GreedyMini

      # Install dependencies and compile on macOS
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install boost

      - name: Compile code on macOS
        if: matrix.os == 'macos-latest'
        run: |
          g++ -std=c++20 -O3 -march=native *.cpp -o GreedyMini

      # Install dependencies and compile on Windows
      - name: Set up MSYS2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-boost

      - name: Compile code on Windows
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          g++ -std=c++20 -O3 -I /mingw64/include *.cpp -o GreedyMini.exe

      # Upload compiled binaries as artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GreedyMini
          path: |
            GreedyMini
            GreedyMini.exe
