name: Build Project

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # **Ubuntu Setup**
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev ninja-build

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      # **macOS Setup**
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake boost ninja

      - name: Build on macOS
        if: matrix.os == 'macos-latest'
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      # **Windows Setup**
      - name: Install vcpkg and Boost on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install boost

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        env:
          VCPKG_ROOT: "%CD%\\vcpkg"
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=amd64
          cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake"
          cmake --build build

      # **Upload Artifacts**
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GreedyMini-${{ matrix.os }}
          path: |
            build/GreedyMini*
            build/GreedyMini.exe
